<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{9fb7cb58-d9f1-4206-b911-0a09f555b724}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	ButtonController : ButtonController;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[ButtonController();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>